# Generated by Django 2.0.5 on 2018-05-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Telno', models.CharField(max_length=100)),
            ],
        ),
    ]
