# Generated by Django 2.0.5 on 2018-06-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='labs',
        ),
    ]
