# Generated by Django 2.0.5 on 2018-06-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0002_delete_labs'),
    ]

    operations = [
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Contactno', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
    ]
