# Generated by Django 2.0.5 on 2018-06-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
    ]
